#version 430 core
#extension GL_ARB_gpu_shader_int64 : require
 // inout is same as reference in cpp
 // in is same as read only
 // out means we can't read value that is inside, only write to it

// Global constants
const float FLOAT_MAX = 3.402823466e+38;
const float EPSILON = 1e-6;
const float PI = 3.14;

// Struct types
struct Material {
    vec3 albedo;
    float roughness; // for metal (currently unused)
    vec3 emission;
};

struct Ray {
    vec3 ro;
    float tMin;
    vec3 rd;
    float tMax;
};
void ray_struct_init(inout Ray ray){ // acts as it's constructor
    ray.tMin = 0;
    ray.tMax = FLOAT_MAX;
}

struct Hit {
    float t;
    vec3 p;
    vec3 normal;
    Material mat;
    vec2 uv;
};
void hit_struct_init(inout Hit h){ // acts as it's constructor
    h.t = FLOAT_MAX;
}

struct IntersectResult {
    float t;
    vec2 buv; // barycentric uv (beta, gamma)
    uint closest_tri_index; // index into index buffer
};

void intersectResultInit(out IntersectResult res) {
    res.t = FLOAT_MAX;
    res.buv = vec2(0.0);
    res.closest_tri_index = uint(-1);
}

struct MeshDesc {
    uint offset_v; // position where vertices array is placed
    uint offset_n; // position where normals array is placed
    uint offset_uv; // position where uv's array is placed
    uint offset_c; // position where color array is placed
    uint offset_i; // position where indices array is placed

    uint count_v; // how many vertices there are
    uint count_i; // how many indices there are
};

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (rgba8, binding = 0) uniform image2D u_display_img;
layout (binding = 1) uniform sampler2D u_background_img;
layout (rgba32f, binding = 2) uniform image2D u_accumulated_img;

layout(std430, binding = 3) buffer MeshHandles { uint64_t u_mesh_handles[]; };
layout(std430, binding = 4) buffer MeshDescs { MeshDesc mesh_descs[]; };

layout(std430, binding = 5) buffer IndexBuffer { uint u_index_data[]; };
layout(std430, binding = 6) buffer VertexBuffer { float u_vertex_data[]; };
layout(std430, binding = 7) readonly buffer NormalBuffer { float u_normal_data[]; };
layout(std430, binding = 8) readonly buffer UVBuffer { float u_uv_data[]; };
layout(std430, binding = 9) buffer TransformBuffer { mat4 u_transforms[]; }; // local to world transforms
layout(std430, binding = 10) buffer InvTransformBuffer { mat4 u_inv_transforms[]; }; // world to local transforms


uniform ivec2 u_resolution; // (width, height)

uniform vec3 u_cam_center;
uniform vec3 u_pixel00_loc;
uniform vec3 u_pixel_delta_u;
uniform vec3 u_pixel_delta_v;

uniform uint u_frame_index; // count of how many frames have passed since start of program
uniform float u_environment_light;
uniform int u_max_bounces;
uniform int u_spp;
uniform bool u_accumulate; // on CPU this is called camera_moved
uniform uint u_mesh_count; // number of mesh descriptors

// Random number generator related functions
uint randPcg(inout uint rng_state) {
    uint state = rng_state;
    rng_state = rng_state * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}
float randUniform(inout uint rng_state) {
    // lower 8 bits are just noice (coming from precision loss).
    // So we shift those lower 8 bits, and than divide by rest 2^24 (since we are left with 24 bits).
    return float(randPcg(rng_state) >> 8u) * (1.0 / 16777216.0);
}
vec3 randomVec3(inout uint rng_state) { // always return in range [0,1].
    // If we need in a different range, we can convert on the place where it is needed.
    return vec3(
        randUniform(rng_state),
        randUniform(rng_state),
        randUniform(rng_state)
    );
}
vec3 randomUnitVector(inout uint rng_state) {
    while (true) {
        vec3 p = randomVec3(rng_state) * 2.0 - 1.0;
        float lensq = dot(p, p);
        if (lensq > 1e-160 && lensq <= 1.0) {
            return p / sqrt(lensq);
        }
    }
}

// Utility functions
float atan2(float y, float x) {
    float s = abs(x) > abs(y) ? 1.0 : 0.0;
    return mix(PI / 2.0 - atan(x, y), atan(y, x), s);
}

// The name comes from the equirectangular projection (also called lat-long mapping), which is a very common way of mapping
// a 3D direction vector onto a 2D texture.
vec2 directionToEquirecangularUV(in vec3 rd){
    float u = (atan2(-rd.z, rd.x) + PI) / (2 * PI);
    float v = acos(-rd.y) / PI;
    return vec2(u, v);
}

void getRay(float i, float j, vec2 offset, out Ray ray) {
    // Construct a camera ray originating from the origin and directed at randomly sampled point around the pixel location i, j.
    // Jitter is the process of selecting random offsets inside the pixel. 
    vec3 pixel_sample = u_pixel00_loc
        + ((i + offset.x) * u_pixel_delta_u)
        + ((j + offset.y) * u_pixel_delta_v);

    ray.ro = u_cam_center;
    ray.rd = normalize(pixel_sample - ray.ro);
}

vec3 transformPoint(vec3 pos, mat4 m) {
    vec4 homogenous_pos = vec4(pos, 1.0);
    vec4 transformed_pos = m * homogenous_pos;
    // Convert back to a 3D position by dividing by w (perspective division, if necessary)
    return transformed_pos.xyz;
}

vec3 transformDirection(vec3 dir, mat3 m) {
    vec3 transformed_dir = m * dir;
    return normalize(transformed_dir);
}

// Utility functions for meshes
uvec3 getIndices(MeshDesc desc, uint tri_idx) {
    uint base = desc.offset_i + tri_idx;
    return uvec3(
        u_index_data[base + 0u],
        u_index_data[base + 1u],
        u_index_data[base + 2u]
    );
}
void getVertices(MeshDesc desc, uvec3 idx, out vec3 v0, out vec3 v1, out vec3 v2) {
    uint base0 = desc.offset_v + idx.x * 3u;
    uint base1 = desc.offset_v + idx.y * 3u;
    uint base2 = desc.offset_v + idx.z * 3u;

    v0 = vec3(
        u_vertex_data[base0 + 0u],
        u_vertex_data[base0 + 1u],
        u_vertex_data[base0 + 2u]
    );
    v1 = vec3(
        u_vertex_data[base1 + 0u],
        u_vertex_data[base1 + 1u],
        u_vertex_data[base1 + 2u]
    );
    v2 = vec3(
        u_vertex_data[base2 + 0u],
        u_vertex_data[base2 + 1u],
        u_vertex_data[base2 + 2u]
    );
}
void getNormals(MeshDesc desc, uvec3 idx, out vec3 n0, out vec3 n1, out vec3 n2) {
    uint base0 = desc.offset_n + idx.x * 3u;
    uint base1 = desc.offset_n + idx.y * 3u;
    uint base2 = desc.offset_n + idx.z * 3u;

    n0 = vec3(
        u_normal_data[base0 + 0u],
        u_normal_data[base0 + 1u],
        u_normal_data[base0 + 2u]
    );
    n1 = vec3(
        u_normal_data[base1 + 0u],
        u_normal_data[base1 + 1u],
        u_normal_data[base1 + 2u]
    );
    n2 = vec3(
        u_normal_data[base2 + 0u],
        u_normal_data[base2 + 1u],
        u_normal_data[base2 + 2u]
    );
}

void getUVs(MeshDesc desc, uvec3 idx, out vec2 uv0, out vec2 uv1, out vec2 uv2) {
    uint base0 = desc.offset_uv + idx.x * 2u;
    uint base1 = desc.offset_uv + idx.y * 2u;
    uint base2 = desc.offset_uv + idx.z * 2u;

    uv0 = vec2(
        u_uv_data[base0 + 0u],
        u_uv_data[base0 + 1u]
    );
    uv1 = vec2(
        u_uv_data[base1 + 0u],
        u_uv_data[base1 + 1u]
    );
    uv2 = vec2(
        u_uv_data[base2 + 0u],
        u_uv_data[base2 + 1u]
    );
}

// Material utility functions
vec3 emitted(in Hit h) {
    return h.mat.emission;
}

bool scatterLambertian(inout uint rng_state, Hit rec, out vec3 attenuation, out vec3 new_dir) {
    vec3 scatter_direction = normalize(rec.normal + randomUnitVector(rng_state));

    if (length(scatter_direction) < EPSILON) scatter_direction = rec.normal;
    new_dir = scatter_direction;
    attenuation = rec.mat.albedo;
    return true;
}

// Hit Object functions
bool hitRectangle(in vec3 rect_p1, in vec3 rect_p2, in vec3 rect_p3, in vec3 rect_p4, in Material mat, in Ray ray, out Hit h) {
    //rect_p1 - bottom-left, rect_p2 - bottom-right, rect_p3 - top-right, rect_p4 - top-left

    vec3 rectangle_normal = normalize(cross(rect_p2 - rect_p1, rect_p3 - rect_p1));

    float c = dot(rectangle_normal, rect_p1);
    float denominator = dot(rectangle_normal, ray.rd);
    if (abs(denominator) < EPSILON) return false;

    float t = (c - dot(rectangle_normal, ray.ro)) / denominator;
    if (t < 0.001) return false;

    vec3 Q = ray.ro + t * ray.rd;
    if (dot(cross((rect_p2 - rect_p1), (Q - rect_p1)), rectangle_normal) < 0 ||
        dot(cross((rect_p3 - rect_p2), (Q - rect_p2)), rectangle_normal) < 0 ||
        dot(cross((rect_p4 - rect_p3), (Q - rect_p3)), rectangle_normal) < 0 ||
        dot(cross((rect_p1 - rect_p4), (Q - rect_p4)), rectangle_normal) < 0) {
        return false;
    }

    h.t = t;
    h.p = Q; // hit point

    vec3 N = normalize(rectangle_normal);
    if (dot(N, ray.rd) > 0.0) N = -N;
    h.normal = N;
    h.mat.albedo = mat.albedo;
    h.mat.emission = mat.emission;
    return true;
}

bool hitTriangle(in vec3 tri_v0, in vec3 tri_v1, in vec3 tri_v2, in Material mat, in Ray ray, out Hit h) {
    // Moeller Trumbore

    vec3 edge1 = tri_v1 - tri_v0;
    vec3 edge2 = tri_v2 - tri_v0;

    vec3 p  = cross(ray.rd, edge2);
    float det = dot(edge1, p);

    if (abs(det) < EPSILON) return false;

    float inv_det = 1.0 / det;
    vec3 s = ray.ro - tri_v0;
    float u = inv_det * dot(s, p);

    if (u < 0.0 || u > 1.0) return false;

    vec3 q = cross(s, edge1);
    float v = inv_det * dot(ray.rd, q);

    if (v < 0.0 || u + v > 1.0) return false;

    float t = inv_det * dot(edge2, q);
    if (t < 0.001) return false;

    h.t = t;
    h.p = ray.ro + t * ray.rd; // hit point

    vec3 N = normalize(cross(edge1, edge2));
    if (dot(N, ray.rd) > 0.0) N = -N;
    h.normal = N;
    h.mat.albedo = mat.albedo;
    h.mat.emission = mat.emission;
    return true;
}

bool intersectTriangleMT(Ray ray, vec3 v0, vec3 v1, vec3 v2, out float t, out float u, out float v) {
    vec3 e1 = v1 - v0;
    vec3 e2 = v2 - v0;
    vec3 p  = cross(ray.rd, e2);
    float det = dot(e1, p);
    if (abs(det) < EPSILON) return false;
    float invDet = 1.0 / det;
    vec3 s = ray.ro - v0;
    u = invDet * dot(s, p);
    
    if (u < 0.0 || u > 1.0) return false;

    vec3 q = cross(s, e1);
    v = invDet * dot(ray.rd, q);
    
    if (v < 0.0 || u + v > 1.0) return false;

    float tt = invDet * dot(e2, q);
    if (tt < 0.001 || tt < ray.tMin || tt > ray.tMax) return false;

    t = tt;
    return true;
}

bool hitSphere(in vec3 sph_center, in float sph_radius, in Material mat, in Ray ray, out Hit h) {
    vec3 oc = sph_center - ray.ro;
    float a = dot(ray.rd, ray.rd);
    float b = dot(ray.rd, oc);
    float c = dot(oc, oc) - sph_radius * sph_radius;
    float discriminant = b*b - a*c;
    if (discriminant < 0.0) return false;

    float sqrtd = sqrt(discriminant);
    float t = (b - sqrtd) / a;
    if (t < 0.001) { 
        t = (b + sqrtd) / a;
        if (t < 0.001) return false;
    }

    vec3 P = ray.ro + t * ray.rd;
    vec3 N = normalize((P - sph_center) / sph_radius);
    if (dot(N, ray.rd) > 0.0) N = -N;

    h.t = t;
    h.p = P; // hit point
    h.normal = N;
    h.mat.albedo = mat.albedo;
    h.mat.emission = mat.emission;
    return true;
}

bool hitMesh(in Ray world_ray, in MeshDesc desc, in Material mat, out Hit out_hit, in uint mesh_index) {
    if (desc.count_i < 3u || desc.count_v == 0u) return false;

    // Get per mesh transforms
    mat4 local_to_world = u_transforms[mesh_index];
    mat4 world_to_local = u_inv_transforms[mesh_index];

    // Transforming ray that is in world space into local space
    Ray local_ray;
    local_ray.ro = transformPoint(world_ray.ro, world_to_local);
    local_ray.rd = transformDirection(world_ray.rd, mat3(world_to_local));

    // Convert boundaries of the ray (tMin/tMax) to local space
    vec3 pmin_world = world_ray.ro + world_ray.rd * world_ray.tMin;
    vec3 pmax_world = world_ray.ro + world_ray.rd * world_ray.tMax;
    vec3 pmin_local = transformPoint(pmin_world, world_to_local);
    vec3 pmax_local = transformPoint(pmax_world, world_to_local);

    float local_min = length(local_ray.ro - pmin_local);
    float local_max = length(local_ray.ro - pmax_local);
    local_ray.tMin = min(local_min, local_max);
    local_ray.tMax = max(local_min, local_max);

    // Best hit info
    float best_t = FLOAT_MAX;
    uint best_i = uint(-1); // closest triangle index
    float best_u = 0.0;
    float best_v = 0.0;

    // Iterate over triangles
    for (uint i = 0u; i < desc.count_i; i += 3u) {
        uvec3 idxs = getIndices(desc, i);

        vec3 v0, v1, v2;
        getVertices(desc, idxs, v0, v1, v2);

        float t, u, v;
        if (intersectTriangleMT(local_ray, v0, v1, v2, t, u, v)) {
            if (t >= local_ray.tMin && t <= local_ray.tMax && t > 0.0 && t < best_t) {
                best_t = t;
                best_i = i;
                best_u = u;
                best_v = v;
            }
        }
    }

    if (best_i == uint(-1) || best_t == FLOAT_MAX) return false;

    // Build local hit
    Hit local_hit;
    hit_struct_init(local_hit);
    local_hit.t = best_t;
    local_hit.p = local_ray.ro + best_t * local_ray.rd;

    uvec3 best_idxs = getIndices(desc, best_i);
    vec3 lv0, lv1, lv2;
    getVertices(desc, best_idxs, lv0, lv1, lv2);

    vec3 geomN_local = normalize(cross(lv1 - lv0, lv2 - lv0));
    if (dot(geomN_local, local_ray.rd) > 0.0) geomN_local = -geomN_local;
    local_hit.normal = geomN_local;
    local_hit.mat = mat;
    local_hit.uv = vec2(best_u, best_v);

    // Convert local hit back to world space
    vec3 p_world = transformPoint(local_hit.p, local_to_world);
    mat3 normalMat = transpose(inverse(mat3(local_to_world)));
    vec3 n_world = normalize(normalMat * local_hit.normal);

    float t_world = length(world_ray.ro - p_world);

    out_hit = local_hit;
    out_hit.p = p_world;
    out_hit.normal = n_world;
    out_hit.t = t_world;

    if (any(isnan(out_hit.normal)) || any(isnan(out_hit.p)) || !(out_hit.t > 0.0)) return false;

    return true;
}

bool hitScene(inout Ray ray, inout Hit closest_hit) {
    // Materials
    Material red;   red.albedo = vec3(0.65, 0.05, 0.05); red.emission = vec3(0.0);
    Material green; green.albedo = vec3(0.12, 0.45, 0.15); green.emission = vec3(0.0);
    Material white; white.albedo = vec3(0.73); white.emission = vec3(0.0);
    Material light; light.albedo = vec3(0.0); light.emission = vec3(15.0); // strong emission

    Material debug_mat; debug_mat.albedo = vec3(1.0,0.0,0.0); debug_mat.emission = vec3(0.0);
    // Meshes
    for (uint m = 0u; m < u_mesh_count; m++) {
        Hit mh;
        hit_struct_init(mh);
        uint handle = uint(u_mesh_handles[m]); // casted to uint32
        if (hitMesh(ray, mesh_descs[handle], debug_mat, mh, m) && mh.t < closest_hit.t) closest_hit = mh;
    }

    return closest_hit.t < FLOAT_MAX;
}

vec3 tracePath(inout Ray ray, inout uint rng_state) {
    vec3 result = vec3(0.0, 0.0, 0.0);
    vec3 attenuation = vec3(1.0);

    for (uint depth = 0; depth <= u_max_bounces; depth++) { // max bounces
        Hit h;
        hit_struct_init(h);

        if(!hitScene(ray, h)){
            // background
            vec2 uv = directionToEquirecangularUV(ray.rd);
            vec3 bg = texture(u_background_img, vec2(uv.x, 1-uv.y)).rgb;
            result += attenuation * bg;
            break;
        }

        vec3 new_dir;
        vec3 new_attenuation;

        vec3 color_from_emission = emitted(h);
        result += attenuation * color_from_emission;

        scatterLambertian(rng_state, h, new_attenuation, new_dir);

        attenuation *= new_attenuation;
        ray.ro = h.p + h.normal * 0.0001; // offset to avoid self-hit
        ray.rd = new_dir;
    }
    
    return result;
}


void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    if (gid.x >= u_resolution.x || gid.y >= u_resolution.y) return;

    uint rng_state = uint(gid.x) + uint(gid.y) * uint(u_resolution.x) + u_frame_index * uint(u_resolution.x) * uint(u_resolution.y);

    float i = float(gid.x) + 0.5;
    float j = float(gid.y) + 0.5;
    vec3 pixel_pos = u_pixel00_loc + i * u_pixel_delta_u + j * u_pixel_delta_v;

    vec3 color = vec3(0.0);
    for(uint samp = 0; samp < u_spp; samp++){
        // Vector to a random point in the [-.5,-.5]-[+.5,+.5] unit square.
        vec2 offset = vec2(randUniform(rng_state) - 0.5, randUniform(rng_state) - 0.5);

        Ray ray;
        ray_struct_init(ray);
        getRay(float(gid.x), float(gid.y), offset, ray);

        color += tracePath(ray, rng_state);
    }
    color /= u_spp;

    // Load previous accumulation
    vec4 prev_accum = imageLoad(u_accumulated_img, gid);

    // Extract sum and count
    vec3 accum_sum = prev_accum.rgb;
    uint count = floatBitsToUint(prev_accum.a);

    // If camera moved, reset accumulation
    if (u_accumulate) {
        accum_sum = color; // start new sum
        count = 1u; // reset accumulated frame counter
    }
    else {
        accum_sum += color;
        count += 1u; // increment accumulated frame counter
    }

    // Compute average
    vec3 avg_color = accum_sum / float(count);

    // Store back into accumulation buffer
    imageStore(u_accumulated_img, gid, vec4(accum_sum, uintBitsToFloat(count)));

    // Display final averaged color
    imageStore(u_display_img, gid, vec4(avg_color, 1.0));
}
